name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/debug
        key: ${{ runner.os }}-stable-cache-${{ hashFiles('**/Cargo.lock') }}
        restore_keys: |
          ${{ runner.os }}-stable-cache-
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
